# Generated by Django 3.2 on 2023-04-11 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("yamdb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titles",
            name="genre",
        ),
        migrations.CreateModel(
            name="GenreTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yamdb.genres",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yamdb.titles",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="titles",
            name="genre",
            field=models.ManyToManyField(
                through="yamdb.GenreTitle", to="yamdb.Genres"
            ),
        ),
    ]
