# Generated by Django 3.2 on 2023-04-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0002_auto_20230422_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
