# Generated by Django 3.2 on 2023-04-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yamdb", "0002_auto_20230412_0254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titles",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
    ]
