# Generated by Django 3.2 on 2023-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yamdb", "0003_alter_titles_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="id",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
