# Generated by Django 3.2 on 2023-04-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0009_auto_20230419_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
